# fly.toml app configuration file generated for lynk-wishlist-dev on 2023-11-20T22:20:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lynk-wishlist-dev"
primary_region = "ams"

[build]
