name: Deploy

env:
  SHOPIFY_APP_URL: ${{ secrets.SHOPIFY_APP_URL }}
  SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
  SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
  SHOPIFY_API_SCOPES: ${{ secrets.SHOPIFY_API_SCOPES }}
  SHOPIFY_API_VERSION: ${{ secrets.SHOPIFY_API_VERSION }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  ENCRYPTION_STRING: ${{ secrets.ENCRYPTION_STRING }}
  NPM_CONFIG_FORCE: true
  VITE_SHOPIFY_API_KEY: ${{ secrets.VITE_SHOPIFY_API_KEY }}
  

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: lynkdom
      
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        run: echo ${{ secrets.SHOPIFY_APP_URL }}

      - name: Setup Node
        run: echo TOKEN ${{ secrets.GITHUB_TOKEN }}
