name: Deploy

env:
  SHOPIFY_APP_URL: ${{ secrets.SHOPIFY_APP_URL }}
  SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
  SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
  SHOPIFY_API_SCOPES: ${{ secrets.SHOPIFY_API_SCOPES }}
  SHOPIFY_API_VERSION: ${{ secrets.SHOPIFY_API_VERSION }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  ENCRYPTION_STRING: ${{ secrets.ENCRYPTION_STRING }}
  NPM_CONFIG_FORCE: true
  VITE_SHOPIFY_API_KEY: ${{ secrets.VITE_SHOPIFY_API_KEY }}
  

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: lynkdom
      
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: client-bundle
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: client-bundle
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
